"""
ask-demo — minimal demo for the agent ↔ user Q&A channel.

Pipeline: greet → confirm. The agent asks the user for their name and an
optional confirmation, then echoes a friendly summary back.

Run standalone (you'll need to feed answer JSONL on stdin manually):
    python main.py
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Make `agent_util` importable from the parent agents/ directory.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from agent_util import (  # noqa: E402
    ask_user,
    artifact,
    done,
    emit_error,
    node_end,
    node_start,
    token,
)


def main() -> int:
    parser = argparse.ArgumentParser(description="Demo agent that asks the user a question.")
    parser.add_argument("--greeting", default="Hi", help="Opening word to use.")
    args = parser.parse_args()

    try:
        node_start("greet", {"greeting": args.greeting})
        token("hello — let's get acquainted.", node="greet")
        name = ask_user("What is your name?", node="greet")
        token(f"got it: {name}", node="greet")
        node_end("greet", progress=0.5)

        node_start("confirm")
        choice = ask_user(
            f"Is '{name}' how you'd like me to address you?",
            choices=["Yes", "No"],
            node="confirm",
        )
        if choice.strip().lower().startswith("n"):
            new_name = ask_user("What name should I use instead?", node="confirm")
            name = new_name
        token(f"{args.greeting}, {name}!", node="confirm")
        artifact(
            "greeting.md",
            "md",
            f"# {args.greeting}, {name}!\n\nGenerated by ask-demo.\n",
            node="confirm",
        )
        node_end("confirm", progress=1.0)

        done(ok=True, summary=f"Greeted {name}")
        return 0
    except Exception as e:  # noqa: BLE001
        emit_error(str(e))
        done(ok=False, error=str(e))
        return 1


if __name__ == "__main__":
    sys.exit(main())
